<?php
/**
 * Page chrome. Scumhouse renders its game screen on the CLIENT (public/js/game.js)
 * rather than server-side like the other games in this repo -- it has to, because
 * the server cannot render a card it is not allowed to know. So this file is just
 * the shell: head, nav, foot.
 */
require_once __DIR__ . '/db.php';

/**
 * The committed SRI manifest (public/integrity.json, generated by
 * tools/integrity.sh).
 *
 * Read from the manifest and NOT recomputed from the file being served: a server
 * that hashes what it is about to serve always agrees with itself, which proves
 * nothing to anybody. Reading a committed file means tampering with the deployed
 * JavaScript alone breaks the page loudly, and tampering with both means editing
 * something with a git history.
 */
function sh_integrity(): array
{
    static $manifest = null;
    if ($manifest === null) {
        $raw = @file_get_contents(__DIR__ . '/../public/integrity.json');
        $data = $raw === false ? null : json_decode($raw, true);
        $manifest = is_array($data) && isset($data['files']) ? $data['files'] : [];
    }
    return $manifest;
}

function sh_e(?string $s): string
{
    return htmlspecialchars((string) $s, ENT_QUOTES, 'UTF-8');
}

function sh_head(string $title, array $user = null, array $extraScripts = []): void
{
    $app = APP_PATH;
    echo '<!doctype html><html lang="en"><head><meta charset="utf-8">';
    echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
    echo '<title>' . htmlspecialchars($title) . ' -- Scumhouse</title>';
    echo '<link rel="stylesheet" href="' . $app . '/css/style.css">';
    // Anonymous endpoints must never see a referrer that names the game screen.
    echo '<meta name="referrer" content="no-referrer">';
    $integrity = sh_integrity();
    foreach ($extraScripts as $src) {
        $key = ltrim($src, '/');
        // Fail loudly rather than quietly serving an unpinned script: a silently
        // dropped integrity attribute is exactly the regression this guards against.
        if (!isset($integrity[$key])) {
            throw new RuntimeException("no integrity hash for $key -- run tools/integrity.sh");
        }
        echo '<script src="' . $app . $src . '" integrity="' . sh_e($integrity[$key]) . '" defer></script>';
    }
    echo '</head><body><header class="sh-top"><a class="sh-brand" href="' . $app . '/lobby.php">Scumhouse</a>';
    echo '<nav><a href="' . $app . '/rules.php">Rules</a>';
    if ($user !== null) {
        echo '<a href="' . APP_PATH . '/account.php">Account</a>';
        echo '<span class="sh-who">' . htmlspecialchars($user['display_name']) . '</span>';
        echo '<a href="' . $app . '/auth/logout.php">Log out</a>';
    }
    echo '</nav></header><main>';
}

function sh_foot(): void
{
    echo '</main><footer class="sh-foot">';
    // Optional link back to whatever site hosts this install. Config-driven so the
    // published source names no particular deployment; omitted entirely when unset.
    $portal = config()['portal_url'] ?? null;
    if (is_string($portal) && $portal !== '') {
        $label = preg_replace('#^https?://#', '', rtrim($portal, '/'));
        echo '<a href="' . sh_e($portal) . '">' . sh_e($label) . '</a> &middot; ';
    }
    echo '<a href="' . APP_PATH . '/rules.php#privacy">What the server can and cannot see</a>';
    echo ' &middot; <a href="' . APP_PATH . '/verify.php">Verify the code</a>';
    echo '</footer></body></html>';
}
