#!/usr/bin/env bash
#
# Generates or checks public/integrity.json -- the SRI manifest for the scripts
# that handle key material.
#
# WHY A COMMITTED MANIFEST AND NOT A HASH COMPUTED AT RENDER TIME:
# a server that hashes the file it is about to serve will always agree with
# itself. That is theatre. The manifest is generated here, committed to git, and
# read by inc/render.php at render time -- so tampering with the deployed
# JavaScript alone makes the browser refuse to run it, and tampering with both
# means editing a tracked file with a visible history.
#
# This does not make the operator untrustworthy-proof. Nothing served by the
# operator can. What it buys is that a backdoor has to be PUBLISHED rather than
# slipped in, and that tools/monitor-integrity.sh -- run from somewhere the
# operator does not control -- will see it.
#
#   tools/integrity.sh          regenerate the manifest
#   tools/integrity.sh --check  fail if the manifest and the files disagree
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/public/integrity.json"

# Only files that can see private keys or drive the protocol. The stylesheet is
# not here because it cannot exfiltrate anything.
FILES=(js/crypto.js js/game.js)

sri() { openssl dgst -sha384 -binary "$1" | openssl base64 -A; }

if [[ "${1:-}" == "--check" ]]; then
  status=0
  for f in "${FILES[@]}"; do
    want=$(python3 -c "import json,sys;print(json.load(open('$MANIFEST'))['files'].get('$f',''))")
    have="sha384-$(sri "$ROOT/public/$f")"
    if [[ "$want" != "$have" ]]; then
      echo "INTEGRITY MISMATCH  $f"
      echo "  manifest: ${want:-<missing>}"
      echo "  on disk:  $have"
      status=1
    fi
  done
  [[ $status -eq 0 ]] && echo "integrity: manifest matches all $(( ${#FILES[@]} )) files"
  exit $status
fi

{
  echo '{'
  echo '  "_comment": "Generated by tools/integrity.sh. Committed on purpose -- see that script for why a render-time hash would prove nothing.",'
  echo "  \"files\": {"
  last=$(( ${#FILES[@]} - 1 ))
  for i in "${!FILES[@]}"; do
    f="${FILES[$i]}"
    comma=","
    [[ $i -eq $last ]] && comma=""
    echo "    \"$f\": \"sha384-$(sri "$ROOT/public/$f")\"$comma"
  done
  echo '  }'
  echo '}'
} > "$MANIFEST"

echo "wrote $MANIFEST"
cat "$MANIFEST"
